---
title: "Bootstrapping"
author: "Xiaoyu Wu"
date: "2023-11-14"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
set.seed(1)
```

## Bootstrapping in SLR

```{r}
n_samp = 250

sim_df_const = 
  tibble(
    x = rnorm(n_samp, 1, 1),
# will generate n_samp number of random values from a normal distribution with a mean of 1 and a standard deviation of 1
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )
sim_df_nonconst = sim_df_const |> 
  mutate(
  error = error * .75 * x,
  y = 2 + 3 * x + error
)
```

Plot the datasets
```{r}
sim_df_const |> 
  ggplot(aes(x=x,y=y))+
  geom_point()+
  geom_smooth(method="lm")

sim_df_nonconst |> 
  ggplot(aes(x=x,y=y))+
  geom_point()+
  geom_smooth(method="lm")
```

```{r}
sim_df = 
  bind_rows(const = sim_df_const, nonconst = sim_df_nonconst, .id = "data_source") 
# creating a new variable "data_source" with const and nonconst 
```

```{r}
sim_df |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm") +
  facet_grid(~data_source) 
```

```{r}
lm(y ~ x, data = sim_df_const) |> 
  broom::tidy() |> 
  knitr::kable(digits = 3)
```

```{r}
lm(y ~ x, data = sim_df_nonconst) |> 
  broom::tidy() |> 
  knitr::kable(digits = 3)
```

# Drawing one bootstrap sample

```{r}
boot_sample = function(df) {
  sample_frac(df, replace = TRUE) |> 
    arrange(x)
}
```
Check if this works 
```{r}
boot_sample(sim_df_nonconst) |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .3) +
  stat_smooth(method = "lm")
```

```{r}
boot_sample(sim_df_nonconst) |> 
  (\(data) lm(y ~ x, data = data))() |> 
  broom::tidy()
```

# Drawing many bootstrap samples

```{r}
boot_straps = 
  tibble(strap_number = 1:1000,
          strap_sample = rerun(1000,boot_sample(sim_df_nonconst))) 
# This creates a tibble (a type of data frame in R) with one column named strap_number. The column contains numbers from 1 to 1000. Each number represents an individual bootstrap sample.
boot_straps
```

```{r}
boot_straps |> 
  slice(1:3) |> 
  mutate(strap_sample = map(strap_sample, arrange, x)) |> 
  pull(strap_sample)
# This code takes the first three bootstrap samples from the boot_straps tibble, sorts each of these samples by the column x, and then extracts and returns these sorted samples.
```

```{r}
boot_straps |> 
  slice(1:3) |> 
  unnest(strap_sample) |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm", se = FALSE) +
  facet_grid(~strap_number)
```

# Analyzing bootstrap samples

```{r}
bootstrap_results = 
  boot_straps |> 
  mutate(
    models = map(strap_sample, ~ lm(y ~ x, data = .x) ),
    results = map(models, broom::tidy)) |> 
  select(-strap_sample, -models) |> 
  unnest(results) 

bootstrap_results |> 
  group_by(term) |> 
  summarize(mean_est=mean(estimate), 
    sd_est = sd(estimate)) |> 
  knitr::kable(digits = 3)
```
Look at the distribution 
```{r}
bootstrap_results |> 
  ggplot(aes(x=estimate)) +
  geom_density()+
  facet_wrap(.~term)
```
Construct a bootstrap confidence interval 
```{r}
bootstrap_results |> 
  group_by(term) |> 
  summarize(
    ci_lower = quantile(estimate, 0.025), 
#  It uses the quantile function to find the 2.5th percentile of the estimate column within each group.
    ci_upper = quantile(estimate, 0.975))
# It finds the 97.5th percentile of the estimate column within each group.
```

```{r}
boot_straps |> 
  unnest(strap_sample) |> 
  ggplot(aes(x = x, y = y)) + 
  geom_line(aes(group = strap_number), stat = "smooth", method = "lm", se = FALSE, alpha = .1, color = "blue") +
  geom_point(data = sim_df_nonconst, alpha = .5)
```

# bootstrap using modelr
```{r}
boot_straps = 
  sim_df_nonconst |> 
  modelr::bootstrap(n = 1000,id="strap_number") |> 
  mutate(
    models = map(.x=strap, ~ lm(y ~ x, data = .x) ),
    results = map(models, broom::tidy)) |> 
  select(strap_number, results) |> 
  unnest(results) |> 
  group_by(term) |> 
  summarize(mean_est=mean(estimate), 
    sd_est = sd(estimate))
```


```{r}
sim_df_nonconst |> 
  modelr::bootstrap(n = 1000) |> 
  mutate(
    models = map(strap, \(df) lm(y ~ x, data = df) ),
    results = map(models, broom::tidy)) |> 
  select(-strap, -models) |> 
  unnest(results) |> 
  group_by(term) |> 
  summarize(boot_se = sd(estimate))
```

```{r}
sim_df_const |> 
  modelr::bootstrap(n = 1000) |> 
  mutate(
    models = map(strap, \(df) lm(y ~ x, data = df)),
    results = map(models, broom::tidy)) |> 
  select(-strap, -models) |> 
  unnest(results) |> 
  group_by(term) |> 
  summarize(boot_se = sd(estimate))
```

# Airbnb data
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  drop_na(price, stars) |> 
  select(price, stars, borough, neighborhood, room_type)
```

```{r}
nyc_airbnb |> 
  ggplot(aes(x = stars, y = price, color = room_type)) + 
  geom_point() 
```

```{r}
airbnb_boot_results=
  nyc_airbnb |> 
  filter(borough == "Manhattan") |> 
  drop_na(stars) |>
  modelr::bootstrap(n = 1000,id="strap_number") |> 
  mutate(
    models = map(.x=strap, ~lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)) |> 
  select(strap_number,results) |> 
  unnest(results) 

airbnb_boot_results |> 
  group_by(term) |> 
  summarize(
    mean_est=mean(estimate),
    sd_est=sd(estimate)
  )
```
Compare this to `lm`
```{r}
nyc_airbnb |> 
  filter(borough == "Manhattan") |> 
  drop_na(stars) |> 
  (\(data) lm(price ~ stars, data = data))() |> 
  broom::tidy()
```

```{r}
airbnb_boot_results |> 
  filter(term=="stars") |> 
  ggplot(aes(x=estimate)) +
  geom_density()
```

